Add exact match configuration to repeated shape name validator
awslabs/smithy pull request #1041
Opened 2022-01-07 17:32 UTC by JordonPhillips

This adds a configuration option to the repeating shape name validator to specify that it should be an exact match rather than a prefix check.

This also deprecates the old validator in favor of the new one due to its less than ideal name.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-07 19:03 UTC, mtdowling requested changes

2022-01-07 19:08 UTC, kstich requested changes

2022-01-07 19:08 UTC, kstich commented on smithy-linters/src/main/java/software/amazon/smithy/linters/RepeatedShapeNameValidator.java
> +    public static final class Config {
This configuration isn't mentioned in the spec.

2022-01-07 19:08 UTC, kstich commented on smithy-linters/src/main/java/software/amazon/smithy/linters/RepeatedShapeNameValidator.java
> +                        + "prefixed with the %2$s name.", shapeName, shape.getType(), memberName));
Should `prefixed` toggle with the `getExactMatch` status?

2022-01-10 16:35 UTC, kstich approved these changes

2022-01-10 17:36 UTC, mtdowling approved these changes

2022-01-10 17:38 UTC, merged