Add support for conditions and loops to AbstractCodeWriter
awslabs/smithy pull request #1144
Opened 2022-03-21 18:23 UTC by mtdowling

AbstractCodeWriter now supports Mustache-like behavior by allowing conditions and loops to be evaluated in templates. Note that this does disallow using '/', '?', '^', and '#' as formatters.

Conditions are defined using `${?foo}` where "foo" is the writer named parameter to evaluate. `?` is used to check if a value is truthy.

The following template with a "foo" value set to "Noid":

```
${?foo}
Hello, ${foo:L}!
${/foo}
```

Evaluates to:

```
Hello, Noid!
```

`^` can be used to check if a value is falsey. The following template with no set "baz" value:

```
${baz}
  Yes baz
${/baz}
${^baz}
  No baz
${/baz}
```

Evaluates to:

```
  No baz
```

A variable is falsey if it is Boolean false, an empty Iterable, an empty Optional, an empty Map, or an empty String. A variable is truthy if it is not falsey.

If a conditional expression or loop expression is the non-whitespace text on a line and is immediately followed by a `\r` or `\n`, then the entire line is omitted from the output.

Loops can be created using `${#foo}`. Each value contained in the referenced named parameter is sent through the contained template, one after the other.

The following template with a "foo" value of ["a", "b"]:

```
${#foo}
- ${currentKey:L}: ${currentValue:L}
${/foo}
```

Evaluates to:

```
- 0: a
- 1: b
```

Each iteration of the loop creates a new state in the writer that sets a named parameter named `currentKey` that contains the current index of the loop or the current key of a map entry; `currentValue` containing the current value of the iterable or current value of a map entry; `currentIsFirst` is set to true when the first value is being evaluated, and `currentIsLast` is set to true when the last value is being evaluated.

```
SimpleCodeWriter writer = new SimpleCodeWriter()
        .trimTrailingSpaces(false)
        .insertTrailingNewline(false);
writer.putContext("foo", Arrays.asList("a", "b", "c"));
writer.write("""
        ${#foo}
        ${?currentIsFirst}
        [
        ${/currentIsFirst}
            ${currentValue:L}${^currentIsLast},${/currentIsLast}
        ${?currentIsLast}
        ]
        ${/currentIsLast}
        ${/foo}""");

assertThat(writer.toString(), equalTo("""
        [
            a,
            b,
            c
        ]
        """);
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-21 19:08 UTC, adamthom-amzn commented
I wonder if you could trim down some of the bloat from `currentIsFirst` and `currentKey`, etc. Maybe something overly complicated and bad like

```
SimpleCodeWriter writer = new SimpleCodeWriter()
        .trimTrailingSpaces(false)
        .insertTrailingNewline(false);
writer.putContext("foo", Arrays.asList("a", "b", "c"));
writer.write("""
        ${#foo|k,v}
        ${?kIsFirst}
        [
        ${/kIsFirst}
            ${v:L}${^kIsLast},${/kIsLast}
        ${?kIsLast}
        ]
        ${/kIsLast}
        ${/foo}""");

assertThat(writer.toString(), equalTo("""
        [
            a,
            b,
            c
        ]
        """);
```

2022-03-21 21:43 UTC, mtdowling commented
I pushed an update that allows loops to define a custom key and value variable name. It now defaults to `key`, `key.first`, `key.last`, and `value`.

2022-03-22 22:36 UTC, adamthom-amzn approved these changes

2022-03-23 09:53 UTC, JordonPhillips requested changes

2022-03-23 09:53 UTC, JordonPhillips commented on smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
> + * <p>The following template with a "foo" value of ["a", "b", "c"]:
You say key-value pair but then immediately follow up with a list. Either this first example should use a map, or the explanation that iterables use the index as a pseudo-key needs to come before this example.

2022-03-23 09:53 UTC, JordonPhillips commented on smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
> + * to falsey, then the template expands to nothing:
```suggestion
 * to falsey, then the template expands to an empty string:
```

2022-03-23 09:53 UTC, JordonPhillips commented on smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
> + * <p>Whitespace that comes before an expression removed by putting "~" at the beginning of an expression.
```suggestion
 * <p>Whitespace that comes before an expression can be removed by putting "~" at the beginning of an expression.
```

2022-03-23 18:34 UTC, merged