Make payload strings and blobs required/default
awslabs/smithy pull request #1209
Opened 2022-04-28 14:03 UTC by JordonPhillips

Strings and blobs bound to the payload have always had an implicit default value, and this pr makes that status explicit by requiring that such members have either the required or the default trait.

1.0 models will have the default trait applied automatically, but it must be explicitly added in 2.0 models.

Since the upgrade tool already supports inserting implicitly added default traits, it needs no updates to handle this. Test cases were added though just to be safe.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-02 15:56 UTC, kstich requested changes

2022-05-02 15:56 UTC, kstich commented on smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelUpgrader.java
> +                && member.getMemberTrait(model, StreamingTrait.class).isPresent()
`@streaming` can only be on the `target` and can only target `blob` for defaulting purposes, simplifying this a little.

2022-05-02 15:56 UTC, kstich commented on smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelUpgrader.java
> +            // the member has the http payload trait, which implies a default in 2.0
Should be updated to reflect streaming related behavior.

2022-05-02 15:56 UTC, kstich commented on smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpPayloadValidator.java
> +        return (target.isStringShape() || target.isBlobShape())
`@streaming` can only be on the `target` and can only target `blob` for defaulting purposes, simplifying this a little.

2022-05-02 15:56 UTC, kstich commented on smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpPayloadValidator.java
> +                    "Members marked with the `httpPayload` trait and `streaming` trait that target strings or "
Can remove `strings or` since they can't be streaming.

2022-05-02 15:56 UTC, kstich commented on smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/upgrade/cases/http-payload.v1.smithy
> +    @streaming
This should be on the targeted shape and is [only valid on `blob`](https://awslabs.github.io/smithy/1.0/spec/core/stream-traits.html#streaming-trait). Needs updating in a few places and in the upgrade.

2022-05-02 15:56 UTC, kstich commented on docs/source/1.0/guides/migrating-idl-1-to-2.rst
> +        @streaming
This should be on the targeted shape and is [only valid on `blob`](https://awslabs.github.io/smithy/1.0/spec/core/stream-traits.html#streaming-trait). Needs updating in a few places.

2022-05-12 19:28 UTC, kstich approved these changes

2022-05-13 16:55 UTC, JordonPhillips commented on docs/source/1.0/spec/core/traits/behavior-traits.rst.template
> +    .. warning::
<img width="831" alt="Screenshot 2022-05-13 at 18 54 28" src="https://user-images.githubusercontent.com/2643092/168331764-7fb19064-a9c3-415b-b8b7-a06006c9decf.png">

This is pulled from the CI-built docs. It looks fine to me

2022-05-13 17:00 UTC, JordonPhillips commented on docs/source/1.0/spec/core/traits/http-traits.rst.template
> +
<img width="593" alt="Screenshot 2022-05-13 at 18 59 59" src="https://user-images.githubusercontent.com/2643092/168332609-03facfc5-09d9-49b0-9285-a7ddcdae0431.png">

Looks fine to me (this also comes from the CI's doc build), though I can remove this anyway

2022-05-13 18:31 UTC, mtdowling commented on docs/source/1.0/spec/core/traits/http-traits.rst.template
> +
thanks for confirming

2022-05-13 18:31 UTC, mtdowling approved these changes

2022-05-20 14:42 UTC, merged