Implement toNode for partition models
awslabs/smithy pull request #1449
Opened 2022-10-13 20:57 UTC by ganeshnj

*Issue #, if available:*

*Description of changes:*

## Motivation

Currently I'm relying on the internal APIs to get the node for partitions in Swift SDK which we must not given how partitions are managed is totally internal details.

```java
val partitions = DefaultPartitionDataProvider::class.java.getResourceAsStream("/software/amazon/smithy/rulesengine/language/partitions.json")
writer.write("private let partitions = \$S", Node.printJson(Node.parse(partitions)))
```

## Changes

This change makes Parititions class Node convertible.

## Result

I could do
```java
val partitions = DefaultPartitionDataProvider().loadPartitions()
writer.write("private let partitions = \$S", Node.printJson(partitions.toNode()))
 ```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-17 11:24 UTC, JordonPhillips commented
Can we get a quick test case please?

2022-10-17 11:31 UTC, JordonPhillips requested changes
Lets add a quick test case please

2022-10-17 15:53 UTC, ganeshnj commented
> Lets add a quick test case please

Added one.

2022-10-18 10:41 UTC, JordonPhillips approved these changes

2022-10-18 23:02 UTC, mtdowling approved these changes

2022-10-18 23:02 UTC, merged