Add Maven dependency resolution to the CLI
awslabs/smithy pull request #1486
Opened 2022-11-01 20:56 UTC by mtdowling

This commit adds the ability to resolve dependencies in the Smithy CLI. This allows end users to author models, generate code, and other activities from the Smithy CLI without needing to use tools like Gradle or Maven. This lowers the up-front learning curve of most Smithy use cases to author models and generate code. Writing Java library code, model build plugins, or transforms is out of scope of the Smithy CLI. Such use cases require the use of tools like Gradle or Maven.

To add dependencies, update smithy-build.json with a "maven" key-value pair, which takes "dependencies" and "repositories":

```
{
    "version": "1.0",
    "maven": {
        "dependencies": ["software.amazon.smithy:smithy-aws-traits:1.26.0"]
    }
}
```

When no "repositories" are present, the CLI assumes Maven Central. When the repository member is set, there are no defaults.

```
{
    "version": "1.0",
    "maven": {
        "repositories": [
            {
                "url": "https://example.com",
                "httpCredentials": "${USERNAME}:${PASSWORD}"
            }
        ],
        "dependencies": ["software.amazon.smithy:smithy-aws-traits:1.26.0"]
    }
}
```

To support dependency resolution in the CLI, this commit also introduces the ``--version`` option to display the current version.

```
smithy --version
1.26.0
```

The ``smithy clean`` command was added since it was very useful to test dependency resolution by removing the classpath cache file to force them to be re-resolved.

```
smithy clean
```

Using the Smithy CLI directly means that tools like Gradle aren't automatically detecting the model directory and adding sources. To account for this, the `sources` property was added to smithy-build.json. It acts like `imports`, but the models contained in `sources` are considered part of the model being built rather than just a dependency (i.e., the sources plugin will contain these models).

```
{
    "version": "1.0",
    "sources": ["model"]
}
```

Other changes:
* This commit also prints out more useful exceptions when --stacktrace is on since wrapping things in a DependencyRunnable obscured the underlying issue.
* To actually test maven resolution, this commit also adds integration tests for the CLI (./gradlew :smithy-cli:integ).
* --disable-dependencies can be passed to make the CLI _not_ resolve dependencies. This is useful when using the CLI with other tools that are responsible for resolving dependencies (e.g., Gradle).
* This commit attempts to make GitHub actions run the CLI integration tests when using Java 11+ (not 8 since it relies on using jlink to build the CLI).
* The binaries created by the CLI were renamed to match the naming conventions of other popular projects
* The CLI wrapper bash script was updated to suppress JAVA_OPTS notifications and to improve its performance. The CLI wrapper script is based on the wrapper used by Gradle.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-02 00:06 UTC, mtdowling commented
Converted t draft while I work out the shadow plugin issues and Smithy Gradle plugin issues.

2022-11-02 22:01 UTC, mtdowling commented
Note that I think publishing the CLI JAR is still not working correctly (based on testing it with publishToMavenLocal at least)

2022-11-10 07:02 UTC, kstich requested changes

2022-11-10 19:43 UTC, mtdowling commented on docs/source-2.0/guides/building-models/build-config.rst
> +      * ``com.foo:baz:[1.0,2.0)`` -- 1.0 <= version <= 2.0
Good catch. I expanded this section and updated this to mostly copy the example from the official documentation.

2022-11-10 19:45 UTC, mtdowling commented on smithy-build/src/main/java/software/amazon/smithy/build/model/SmithyBuildConfig.java
> +     *     "sources": ["model"],
added

2022-11-10 19:59 UTC, mtdowling commented on smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ClasspathCommand.java
> +        String version = "[1.25.0," + SmithyCli.getVersion() + ']';
I moved it to a constant with more docs around when to change the value. Basically only when a major version bump is done or some big bug fix is required for the CLI to function.

2022-11-10 20:04 UTC, mtdowling commented on smithy-cli/src/it/java/software/amazon/smithy/cli/IntegUtils.java
> +    public static RunResult run(Path root, List<String> args) {
Yeah those other commands create a workspace for you from a project and run a single command. This particular operation assumes you already have a workspace created and want to run multiple commands.

2022-11-10 20:05 UTC, mtdowling commented on smithy-cli/src/it/java/software/amazon/smithy/cli/SmithyBuildTest.java
> +            assertThat(result.getOutput(), not(containsString("java.io.UncheckedIOException")));
I think that looking for the classname inherently asserts that there's no stacktrace.

2022-11-10 20:07 UTC, kstich commented on smithy-cli/src/it/java/software/amazon/smithy/cli/SmithyBuildTest.java
> +            assertThat(result.getOutput(), not(containsString("java.io.UncheckedIOException")));
Missed that this was a `not` in this test.

2022-11-10 22:48 UTC, kstich commented on docs/source-2.0/guides/building-models/build-config.rst
> +        than or equal to 1.0 and greater than or equal to 2.0.
s/2.0/1.2

2022-11-10 23:58 UTC, kstich approved these changes

2022-11-15 18:29 UTC, kstich approved these changes

2022-12-03 09:41 UTC, closed without merging