Update protocol tests with int enum coverage
awslabs/smithy pull request #1492
Opened 2022-11-08 23:06 UTC by haydenbaker

*Description of changes:*

As part of IDL 2.0, the intEnum shape was added. The following changes add several test cases using an intEnum shape (and/or aggregates) under the protocols test suite. Included is a set of shared types, which target intEnum (or aggregate-shapes of intEnum).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-10 12:31 UTC, JordonPhillips approved these changes

2022-11-10 21:33 UTC, syall requested changes

2022-11-10 21:33 UTC, syall commented on smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy
> +                "b": 1
Found typo when testing it in go codegen:

```suggestion
                "b": 2
```

2022-11-10 22:38 UTC, syall approved these changes

2022-11-11 02:13 UTC, syall requested changes

2022-11-11 02:13 UTC, syall commented on smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy
> +                  <XmlEnumsResult>
```suggestion
                  <XmlIntEnumsResult>
```

2022-11-11 02:13 UTC, syall commented on smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy
> +                  </XmlEnumsResult>
```suggestion
                  </XmlIntEnumsResult>
```

2022-11-11 02:37 UTC, syall requested changes

2022-11-11 23:25 UTC, syall approved these changes

2022-11-14 18:38 UTC, merged