add unix install script for smithy-cli
awslabs/smithy pull request #1657
Opened 2023-03-06 19:03 UTC by haydenbaker

*Issue #, if available:*
N/A

*Description of changes:*
Adds an install script that is to be used by unix-based machines to installing the smithy-cli distributable (and is included in it)

*Testing*
- Build the smithy-cli distributables via `gradlew :smithy-cli:runtime`, and navigate to the respective image for your machine (`smithy-cli/build/image/smithy-cli-<platfrm>/`)
- Run the install script via `./install`
- Optionally, you may configure a custom install and bin directory to use instead of the defaults.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-06 21:42 UTC, mtdowling requested changes

2023-03-06 21:42 UTC, mtdowling commented on smithy-cli/build.gradle
> +            include targetPlatform.value.name.contains("windows") ? "install.bat" : "install"
Where's the .bat file?

2023-03-06 21:42 UTC, mtdowling commented on smithy-cli/config/install
> +# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```suggestion
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```

Can we also use the shorter license header?

2023-03-06 21:42 UTC, mtdowling commented on smithy-cli/config/install
> +	err_msg="$1"
nit - indentation

2023-03-06 21:42 UTC, mtdowling commented on smithy-cli/config/install
> +	case "$key" in
nit - indentation

2023-03-06 21:42 UTC, mtdowling commented on smithy-cli/config/install
> +  echo "You can now run: '$BIN_SMITHY_EXE --version' or '$EXE_NAME --version' if '$BIN_DIR' is already in your \$PATH"
Can we detect if it's in ther path, and if not show a warning? And don't we need to invoke the warmup command too to add the CDS archive?

2023-03-09 17:23 UTC, merged

2023-03-09 20:55 UTC, haydenbaker commented on smithy-cli/config/install
> +#  INSTALL_DIR="$INSTALL_DIR"
Will remove this.