Add examples of validators to documentation
awslabs/smithy pull request #1702
Opened 2023-03-31 14:24 UTC by hpmellema

*Description of changes:*
This pull request adds a number of example linters to as a subpage of the Validator page. 

These examples are not exhaustive, but are intended to show users some of the ways smithy validators can prevent common bugs and enforce a common style in their Smithy models.

*Testing* 
I checked each validator against a local model to make sure error messages formatted correctly and that they could be parsed. Then I generated the docs using the `make html` command and visually checked the generated html.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-05 16:07 UTC, haydenbaker requested changes

2023-04-05 16:07 UTC, haydenbaker commented on docs/source-2.0/guides/model-validation-examples.rst
> +    checks for a common mixin rather than a single operation. See :ref:`Operations Should Use Common Mixin <operations-should-use-common-mixin>`
This is more of a `tip::`, since it's a helpful suggestion to the reader, also "errors you likely" should be "errors, you likely"

2023-04-05 16:07 UTC, haydenbaker commented on docs/source-2.0/guides/model-validation-examples.rst
> +    selector to `[trait|httpHeader^="x-" i]`
Same comment as above, any  time you are suggesting that the reader do something, it's _probably_ a tip versus a note.

2023-04-05 16:57 UTC, hpmellema commented on docs/source-2.0/guides/index.rst
> +    model-validation-examples
I think in this case "model-linters" is defined as: 
"A *linter* is a special kind of model validator that is configurable."
Im not sure the model validators here are really a sub-set of those linters so I'd rather it remain in a separate guide.

2023-04-05 17:09 UTC, mtdowling commented on docs/source-2.0/guides/model-validation-examples.rst
> +======================================================
Yeah, I'm surprised the doc build passed

2023-04-05 17:10 UTC, hpmellema commented on docs/source-2.0/guides/model-validation-examples.rst
> +======================================================
Doc build only checks for < title length, not greater than.

2023-04-07 15:41 UTC, hpmellema commented on docs/source-2.0/guides/index.rst
> +    model-validation-examples
I misunderstood originally. Updated to change order.

2023-04-07 16:07 UTC, haydenbaker commented on docs/source-2.0/guides/model-validation-examples.rst
> +suppressing, and modifying Smithy Validators.
I'm guilty of this often, but we should use qualifiers (`kind of`, `somewhat`, etc.) sparingly in docs. I'd suggest just removing -> 'provides a "cookbook" of examples'

2023-04-07 16:15 UTC, haydenbaker commented on docs/source-2.0/guides/model-validation-examples.rst
> +an httpError trait (and therefore httpError code) defined.
code: ``httpError``

2023-04-07 16:16 UTC, haydenbaker commented on docs/source-2.0/guides/model-validation-examples.rst
> +    This example only makes sense for services using an httpProtocol.
`httpProtocol`

2023-04-07 16:17 UTC, haydenbaker commented on docs/source-2.0/guides/model-validation-examples.rst
> +Case insensitive check for "X-" prefix on all custom httpHeaders used in your
`httpHeaders`

2023-04-07 17:52 UTC, haydenbaker approved these changes

2023-04-07 17:53 UTC, merged