Document changeStringEnumsToEnumShapes transformer
awslabs/smithy pull request #1740
Opened 2023-04-19 16:01 UTC by srchase

Adds docs for changeStringEnumsToEnumShapes transformer, including behavior from https://github.com/awslabs/smithy/pull/1739

Additionally, it updates the `changeTypes` documentation to include its ability to transform Strings with `@enum` traits to Enums.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-19 22:13 UTC, mtdowling requested changes

2023-04-19 22:13 UTC, mtdowling commented on docs/source-2.0/guides/building-models/build-config.rst
> +definitions within the source enum trait must have a `name` property, or the
Need to use double backticks here

2023-04-20 20:49 UTC, gosar approved these changes

2023-04-20 20:49 UTC, gosar commented on docs/source-2.0/guides/building-models/build-config.rst
> +to the resulting enum shape member. If the enum definition is tagged as
Before talking about the special handling for "internal" tag, mention that all tags from enum definition becomes `@tags` trait on the member.

2023-04-20 20:50 UTC, mtdowling commented on docs/source-2.0/guides/building-models/build-config.rst
> +`synthesizeNames` transform config option must be enabled. By default, `synthesizeNames`
```suggestion
``synthesizeNames`` transform config option must be enabled. By default, ``synthesizeNames``
```

2023-04-20 20:58 UTC, gosar commented
This transform is available to 1.0 IDL too, since we load everything as 2.0 and serialize as 2.0 anyways. Should we document this in the 1.0 docs too?

2023-04-20 22:35 UTC, merged