Add validator to check consistency of resource name used for IamResource
awslabs/smithy pull request #1819
Opened 2023-06-13 17:26 UTC by hpmellema

### Background
The [`IamResource`](https://smithy.io/2.0/aws/aws-iam.html#aws-iam-iamresource-trait) trait indicates properties of a Smithy resource in AWS IAM. If no `name` parameter is provided to the `IamResource` trait then a shape's IamResource name is assumed to just be the resource's name, otherwise the `name` parameter is used.

The name of an IamResource is expected to match the name of the resource in the resource's ARN. For examples if the resource has an arn trait of `@arn(template: "my-shape")` then the `IamResource` name should be `"my-shape"` for that resource.

Note: This validator throws a DANGER event instead of an ERROR so that the validation event can be suppressed if needed for backwards compatibility.

### Description of changes:
- Adds new validator and associated unit tests to check that the name specified for the `IamResource` trait is consistent with the resource name in the resource's ARN template

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-14 21:18 UTC, mtdowling requested changes

2023-06-14 21:18 UTC, mtdowling commented on smithy-aws-iam-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
> +software.amazon.smithy.aws.iam.traits.IamResourceTraitValidator
nit - missing newline

2023-06-14 21:18 UTC, mtdowling commented on smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/IamResourceValidatorTest.java
> +public class IamResourceValidatorTest {
Can we take this as an opportunity to add a test runner for .smithy/.errors?

2023-06-14 21:18 UTC, mtdowling commented on smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitValidator.java
> +        return new ArrayList<>(Arrays.asList(arnTemplate.split("/")));
Returning Arrays.asList's result directly doesn't work?

2023-06-14 21:18 UTC, mtdowling commented on smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitValidator.java
> +                    .orElse(StringUtils.lowerCase(resource.getId().getName()));
Use orElseGet when doing a computation like this

2023-06-14 21:18 UTC, mtdowling commented on smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitValidator.java
> +                            "The `@aws.iam#iamResource trait applied to the resource "
```suggestion
                            "The `@aws.iam#iamResource` trait applied to this resource "
```

2023-06-14 21:18 UTC, mtdowling commented on smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitValidator.java
> +                            + "defines a resource name, `%s`, that does not match the `@arn` template, "
Can we be more specific here and say an IAM resource name?

2023-06-14 21:18 UTC, mtdowling commented on smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitValidator.java
> +                            + "`%s`, for that same resource.",
```suggestion
                            + "`%s`, of the resource.",
```

2023-06-20 17:52 UTC, srchase approved these changes

2023-06-20 18:14 UTC, merged