Skip unrecognized JSON files when loading models
awslabs/smithy pull request #1846
Opened 2023-07-05 21:50 UTC by mtdowling

*Issue #, if available:* #1841

*Description of changes:*

This commit updates the model loading process so that JSON files that are not objects or that don't contain a top-level "smithy" key are skipped. This can be useful when loading directories that contain Smithy models mixed with other JSON files. JAR files that contain Smithy models are not permitted to refer to unrecognized JSON files that lack a valid "smithy" version key/value pair.

This commit also only creates InputStreams for files that Smithy can actually load or attempt to load. Smithy would previously open an InputStream for all recursive files in a directory even if it was unable to load the file based on the filename. It now only creates an InputStream when the file has a .json, .smithy, or no file extension.

Closes #1841

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-05 23:26 UTC, kstich requested changes
Looks like issues with Windows CI, I had issues with `Paths.get` formatting Windows paths improperly because they needed to be URIs to encode correctly.

2023-07-05 23:26 UTC, kstich commented on smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelLoader.java
> +            if (model.getStringMap().containsKey("smithy")) {
nit: use `containsMember` for brevity

2023-07-05 23:26 UTC, kstich commented on smithy-model/src/test/java/software/amazon/smithy/model/JarUtils.java
> + * Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
nit: use short header

2023-07-05 23:26 UTC, kstich commented on smithy-model/src/test/java/software/amazon/smithy/model/JarUtils.java
> +     * <p>This method is preferred over embedding JARs directly as resources when possible, because that JARs don't
s/because that JARs/because the JARs

2023-07-06 14:59 UTC, kstich commented on smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
> +        Path jar = JarUtils.createJarFromDir(Paths.get(getClass().getResource("assembler-fail-invalid-jar").getFile()));
I believe the CI is failing here because `.getFile()` should be `.toURI()`.

2023-07-06 19:23 UTC, kstich approved these changes

2023-07-06 19:24 UTC, merged

2023-07-06 22:19 UTC, kubukoz commented
@mtdowling do you have a timeline for the next release? This and #1838 would be really nice to have for my team.

2023-07-06 22:22 UTC, mtdowling commented
We're planning for a Monday release

2023-07-06 22:43 UTC, kubukoz commented
awesome, thanks!