Add methods for retrieving full paginator output and item paths.
awslabs/smithy pull request #628
Opened 2020-11-09 19:14 UTC by skmcgrail

Adds support for retrieving the full list of MemberShape paths for the @paginated.outputToken and @paginated.items paths. Currently marked the old methods as deprecated as to better indicate the more desirable retrievers a user should use.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-11 19:01 UTC, kstich requested changes

2020-11-12 21:17 UTC, JordonPhillips requested changes

2020-11-12 21:17 UTC, JordonPhillips commented on smithy-model/src/main/java/software/amazon/smithy/model/knowledge/PaginationInfo.java
>      public MemberShape getOutputTokenMember() {
You should also decorate the method with `@Deprecated`

2020-11-12 21:17 UTC, JordonPhillips commented on smithy-model/src/main/java/software/amazon/smithy/model/knowledge/PaginationInfo.java
> +    public List<MemberShape> getItemsMemberPath() {
This needs docs

2020-11-12 21:17 UTC, JordonPhillips commented on smithy-model/src/main/java/software/amazon/smithy/model/traits/PaginatedTrait.java
> +    public static List<MemberShape> resolvePathToMember(
nit: `resolveFullPath` would be a better name

2020-11-12 22:07 UTC, JordonPhillips approved these changes

2020-11-16 20:03 UTC, kstich requested changes

2020-11-17 20:05 UTC, mtdowling approved these changes

2020-11-17 21:02 UTC, kstich approved these changes

2020-11-17 21:02 UTC, merged