Add test for map of sets to restJson protocol test.
awslabs/smithy pull request #684
Opened 2021-01-08 02:11 UTC by kggilmer

*Issue #, if available:* N/A

*Description of changes:*

Adds a test to exersize a nested set within a map for `restJson1` protocol.  I had implemented some serialization code but forgot about nested Sets.  Protocol tests as-is didn't catch this case.

## Testing Done

* `./gradlew test`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-08 19:24 UTC, kstich requested changes

2021-01-08 19:24 UTC, kstich commented on smithy-aws-protocol-tests/model/restJson1/json-maps.smithy
> +    denseSetMap: DenseSetMap,
Looks like you added the members to the structures, but didn't update the test contents to utilize them.

2021-01-08 19:24 UTC, kstich commented on smithy-aws-protocol-tests/model/restJson1/json-maps.smithy
> +}
This should have a newline at EOF.

2021-06-11 22:26 UTC, mtdowling approved these changes

2021-06-11 22:51 UTC, kstich approved these changes

2021-06-11 22:52 UTC, merged