Document awsQuery protocol
awslabs/smithy pull request #700
Opened 2021-02-02 02:58 UTC by kstich

This fleshes out the documentation for the `awsQuery` protocol.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-02 02:59 UTC, kstich commented on docs/themes/smithy/static/default.css_t
> +  background-color: #e9e9e9;
Slightly darker to be visible in dark background table rows without being obnoxious in light backgrounds.

2021-02-02 07:02 UTC, JordonPhillips requested changes

2021-02-02 19:05 UTC, kstich commented on docs/source/1.0/spec/aws/aws-query-protocol.rst
> +*TODO: Add event stream handling specifications.*
Going to leave this here until we do the full investigation in to event stream handling.

2021-02-03 11:25 UTC, JordonPhillips requested changes

2021-02-03 11:25 UTC, JordonPhillips commented on docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
> +         - The :token:`member name <shape_id_member>`
This should show up in normal query too

2021-02-03 14:49 UTC, JordonPhillips approved these changes

2021-02-03 16:57 UTC, merged