Make IDL commas whitespace and newlines optional
awslabs/smithy pull request #772
Opened 2021-04-10 04:26 UTC by mtdowling

Commas are now treated as whitespace to reduce visual noise in models,
reduce diff noise when changes are made to models, and prevent modelers
from worrying about tricks like trailing commas. Commas are still
allowed because they do make traits and JSON-like node values defined on
a single line easier to read; however, they should be omitted everywhere
else.

The IDL previously required a newline after various statements. This
wasn't grammatically necessary, but was done to force good practice in
models. However, it added complexity to the grammar and parser. While
models should still define all statements on different lines, to simplify
parsers and the grammar, a new line after statements is no longer
required.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-12 14:15 UTC, JordonPhillips requested changes

2021-04-12 17:58 UTC, mtdowling commented on docs/source/1.0/spec/core/http-traits.rst
>      }
Whoops! Over-eager find and replace :)

2021-04-13 10:33 UTC, JordonPhillips approved these changes

2021-04-13 17:53 UTC, kstich reviewed
Can the example in the README get updated as well?

2021-04-16 00:30 UTC, mtdowling commented on docs/source/1.0/guides/style-guide.rst
> +* Each statement should appear on its own line.
Fixed by just making the statement imperative like other similar statements.

2021-04-16 00:30 UTC, mtdowling commented on docs/source/1.0/guides/style-guide.rst
> +* Commas should be omitted everywhere except in traits or node
Added a "do" and "do not" example

2021-04-16 21:00 UTC, kstich approved these changes

2021-04-21 05:00 UTC, merged