Add rest xml protocol tests for nested maps
awslabs/smithy pull request #777
Opened 2021-04-21 15:12 UTC by JordonPhillips

Resolves #748

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-21 16:23 UTC, srchase approved these changes

2021-04-21 17:22 UTC, kstich requested changes

2021-04-21 17:22 UTC, kstich commented on smithy-aws-protocol-tests/model/restXml/document-maps.smithy
> +                <nestedMap>
This should be `flatNestedMap`.

2021-04-21 17:22 UTC, kstich commented on smithy-aws-protocol-tests/model/restXml/document-maps.smithy
> +                <nestedMap>
This should be `flatNestedMap`.

2021-04-22 21:49 UTC, kstich approved these changes

2021-04-23 13:41 UTC, merged