Add a model for validation errors
awslabs/smithy pull request #813
Opened 2021-05-27 23:06 UTC by adamthom-amzn

Server SDKs need a common, framework-level definition of a validation error
that service authors can opt into.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-28 14:43 UTC, JordonPhillips requested changes

2021-05-28 14:43 UTC, JordonPhillips commented on smithy-validation/src/main/resources/META-INF/smithy/smithy.framework.validation.smithy
> +structure ValidationException {
Let's get some doc comments ('///') on these

2021-06-11 17:18 UTC, gosar approved these changes
LGTM

2021-06-11 19:58 UTC, mtdowling approved these changes

2021-06-11 21:58 UTC, merged