Describe and support non-numeric floats
awslabs/smithy pull request #828
Opened 2021-06-10 16:10 UTC by JordonPhillips

This documents how the non-numeric floating point values `NaN`, `Infinity`, and `-Infinity` are handled in protocols. Essentially they are serialized as the protocol's strings with those values. Protocol tests have been added to each AWS protocol to assert that behavior.

Since JSON explicitly disallows these values, the jsonschema tooling doesn't enable them by default. This was also done because defaulting that behavior would be a breaking change. 

Fixes #812 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-11 21:32 UTC, mtdowling requested changes

2021-06-11 21:32 UTC, mtdowling commented on docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
> +specified, the ``ec2Query`` treats those special values as strings with the
```suggestion
specified, the ``ec2Query`` protocol treats those special values as strings with the
```

2021-06-11 21:32 UTC, mtdowling commented on docs/source/1.0/spec/aws/aws-json.rst.template
> +specified, the |quoted shape name| treats those special values as
```suggestion
specified, the |quoted shape name| protocol treats those special values as
```

2021-06-11 21:32 UTC, mtdowling commented on docs/source/1.0/spec/aws/aws-restxml-protocol.rst
> +specified, the ``aws.protocols#restXml`` treats those special values as
```suggestion
specified, the ``aws.protocols#restXml`` protocol treats those special values as
```

2021-06-11 21:32 UTC, mtdowling commented on docs/source/1.0/spec/aws/aws-restjson1-protocol.rst
> +specified, the ``aws.protocols#restJson1`` treats those special values as
```suggestion
specified, the ``aws.protocols#restJson1`` protocol treats those special values as
```

2021-06-11 21:32 UTC, mtdowling commented on docs/source/1.0/spec/aws/aws-query-protocol.rst
> +specified, the ``awsQuery`` treats those special values as strings with the
```suggestion
specified, the ``awsQuery`` protocol treats those special values as strings with the
```

2021-06-11 21:32 UTC, mtdowling commented on docs/source/1.0/guides/converting-to-openapi.rst
> +supportNonNumericFloats (``boolean``)
Can you show an example of what this generates?

2021-06-11 21:32 UTC, mtdowling commented on smithy-aws-protocol-tests/model/awsJson1_1/json-structs.smithy
> +        body: """
Don't all these tests need a `bodyMediaType: "application/json"`?

2021-06-11 21:32 UTC, mtdowling commented on smithy-aws-protocol-tests/model/awsJson1_0/json-structs.smithy
> +        body: """
These tests need a `bodyMediaType` too.

2021-06-11 21:32 UTC, mtdowling commented on smithy-aws-protocol-tests/model/restJson1/json-structs.smithy
> +    {
These need a `bodyMediaType`

2021-06-11 21:32 UTC, mtdowling commented on smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
> +    private void updateFloatFormat(Schema.Builder builder, JsonSchemaConfig config, String format) {
This is a bit unfortunate. I wonder if later we can rethink the divide between OpenAPI and JSON Schema converters.

2021-06-11 21:32 UTC, mtdowling commented on smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NonNumericFloatValuesPlugin.java
> +final class NonNumericFloatValuesPlugin implements NodeValidatorPlugin  {
Nice! I think the Smithy spec around trait node values needs to be updated too.

2021-06-11 21:42 UTC, kstich requested changes

2021-06-15 17:29 UTC, mtdowling approved these changes

2021-06-16 17:58 UTC, mtdowling approved these changes

2021-06-16 18:02 UTC, kstich approved these changes

2021-06-17 13:47 UTC, merged