Add `@s3UnwrappedXmlOutput` trait to support S3's GetBucketLocation
awslabs/smithy pull request #839
Opened 2021-06-21 17:01 UTC by jdisanti

This PR adds a new `@s3UnwrappedXmlOutput` trait so that the response shape for S3's GetBucketLocation call can be expressed in the Smithy model, and also adds an S3 protocol test to exercise the new trait.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-21 20:24 UTC, kggilmer commented
imho It seems a little weird to create a trait to fix a specific problem on a specific operation, as one would expect traits to be more general purpose.  I'm guessing that this is the approach because, due to the structure of the response, Smithy is unable to describe it.  Would a more general-purpose approach be a trait which would collapse the wrapper of any XML structure/shape, similar to how maps and lists can be flattened?

2021-06-21 22:04 UTC, kstich requested changes

2021-06-22 16:23 UTC, jdisanti commented on smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/customizations/S3UnwrappedXmlOutputTrait.java
> +    public static final ShapeId ID = ShapeId.from("smithy.api#s3UnwrappedXmlOutput");
Good catch! Fixed.

2021-06-22 16:23 UTC, jdisanti commented on docs/source/1.0/spec/aws/customizations/s3-customizations.rst
> +--------------------------
Ah, I didn't notice that. Revised the documentation to match the other trait docs and gave it its own top-level section. Thanks!

2021-06-22 16:29 UTC, jdisanti commented
@kggilmer - The intent is to be able to express S3 in Smithy while avoiding a more generic mechanism that would allow future services to have unwrapped responses like this.

2021-06-23 15:33 UTC, kstich approved these changes

2021-06-23 15:35 UTC, JordonPhillips approved these changes

2021-06-23 15:35 UTC, merged