Some initial malformed request tests
awslabs/smithy pull request #879
Opened 2021-08-03 23:34 UTC by adamthom-amzn

*Description of changes:*
Most of the numeric type tests are based on each other; if you've read one integral one and one floating-point one, you've read them all.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-04 11:00 UTC, JordonPhillips requested changes

2021-08-04 17:18 UTC, adamthom-amzn commented on smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-boolean.smithy
> +            "value" : ["true", "TRUE", "yes", "YES", "1", "false", "FALSE", "no", "NO", "0"]
Yeah, will do.

2021-08-04 17:18 UTC, adamthom-amzn commented on smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-list.smithy
> +apply MalformedList @httpMalformedRequestTests([
I'm going to have a separate set of test cases for default validations, for all constraint traits (including uniqueItems)

2021-08-04 17:19 UTC, adamthom-amzn commented on smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-request-body.smithy
> +            "value": ["{[",
Will add

2021-08-05 14:12 UTC, JordonPhillips approved these changes

2021-08-05 21:38 UTC, merged