add test for rpc protocol path preix
awslabs/smithy pull request #899
Opened 2021-08-30 19:34 UTC by AllanZhengYP

*Description of changes:*

Followup to https://github.com/awslabs/smithy-typescript/pull/406. Add protocol test for RPC protocols path prefix support.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-30 19:58 UTC, adamthom-amzn requested changes
The commit message has a typo - "preix" should be "prefix"

2021-08-30 19:58 UTC, adamthom-amzn commented on smithy-aws-protocol-tests/model/awsJson1_0/endpoint-paths.smithy
> +operation HostWithPathOperation {}
missing newline at end of file

2021-08-30 19:58 UTC, adamthom-amzn commented on smithy-aws-protocol-tests/model/awsQuery/endpoint-paths.smithy
> +operation HostWithPathOperation {}
Also missing a newline here

2021-08-30 19:58 UTC, adamthom-amzn commented on smithy-aws-protocol-tests/model/ec2Query/endpoint-paths.smithy
> +operation HostWithPathOperation {}
Also missing a newline at the end here

2021-08-31 14:39 UTC, JordonPhillips approved these changes

2021-08-31 16:13 UTC, adamthom-amzn approved these changes

2021-08-31 16:14 UTC, merged