Add input and output traits
awslabs/smithy pull request #967
Opened 2021-10-29 23:59 UTC by mtdowling

These traits allow shapes to be specialized as only acting as input or
output for a single operation. This will make it easier to generate code
from Smithy models, and we will be able to give more relaxed backward
compatibility semantics to structures that are marked as `@input`
structures.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-01 15:04 UTC, JordonPhillips requested changes

2021-11-01 16:09 UTC, mtdowling commented on smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/OperationInputOutputValidator.java
> +                        "The %s of this operation should target a shape that starts with the operation's name, '%s', "
I don't think we need to call out inline syntax here. This is a validation event dealing with the semantic model, so I don't think we should call out specific model representations in the validation.

2021-11-01 16:11 UTC, mtdowling commented on smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
> +@trait(selector: "structure", conflicts: [output, error])
Yes, it works with mixins. Every trait works with mixins. I can add a test case.

2021-11-01 16:14 UTC, JordonPhillips commented on smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/OperationInputOutputValidator.java
> +                        "The %s of this operation should target a shape that starts with the operation's name, '%s', "
I disagree. Essentially everyone will be writing models in the IDL format, so giving them guidance on things that can make things easier there will always be better than not. We can preface that with "In the IDL," or something to make it clear when the advice applies though.

2021-11-02 19:00 UTC, mtdowling commented on docs/source/1.0/spec/core/type-refinement-traits.rst
> +   they are associated with.
Good points. I updated this to be a WARNING instead.

2021-11-03 11:42 UTC, JordonPhillips approved these changes

2021-11-13 21:15 UTC, mtdowling commented
Closing in favor of #980

2021-11-13 21:15 UTC, closed without merging